In [6]:
import numpy as np
import pandas as pd

In [9]:
s = pd.read_csv('mnist.csv')

In [10]:
s

,5,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.608,0.609,0.610,0.611,0.612,0.613,0.614,0.615,0.616,0.617
0,#0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
s.to_html('gg.')

<bound method DataFrame.to_html of     5  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.608  0.609  0.610  \
0  #0  0    0    0    0    0    0    0    0    0  ...        0      0      0
1   4  0    0    0    0    0    0    0    0    0  ...        0      0      0
2   1  0    0    0    0    0    0    0    0    0  ...        0      0      0
3   9  0    0    0    0    0    0    0    0    0  ...        0      0      0
4   2  0    0    0    0    0    0    0    0    0  ...        0      0      0
5   1  0    0    0    0    0    0    0    0    0  ...        0      0      0
6   3  0    0    0    0    0    0    0    0    0  ...        0      0      0
7   1  0    0    0    0    0    0    0    0    0  ...        0      0      0

   0.611  0.612  0.613  0.614  0.615  0.616  0.617
0      0      0      0      0      0      0      0
1      0      0      0      0      0      0      0
2      0      0      0      0      0      0      0
3      0      0      0      0      0      0      0
4      0      0      0      0      0      0      0
5      0      0      0      0      0      0      0
6      0      0      0      0      0      0      0
7      0      0      0      0      0      0      0

[8 rows x 785 columns]>